
server:
  port: 80

#客户端注册进eureka服务列表内
eureka:
  client:
    service-url:
      defaultZone: http://${eureka-hostname}:${eureka-port[0]}/eureka/,http://${eureka-hostname}:${eureka-port[1]}/eureka/,http://${eureka-hostname}:${eureka-port[2]}/eureka/
    register-with-eureka: false

eureka-hostname: localhost
eureka-port: [7001,7002,7003]

feign:
  circuitbreaker:
    enabled: true

spring:
  application:
    name: cunsumer-feign-sentinel

---
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080

#---
##使用 feign.circuitbreaker.enabled=true 也是管用的
#feign:
#  sentinel:
#    enabled: true