spring:
  application:
    name: zookeeper-provider
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:mybatis/SqlMapConfig.xml
  type-aliases-package: api.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

server:
  port: 8001

---
spring:
  cloud:
    zookeeper:
      connect-string: ${zookeeper-hostname[0]}:${zookeeper-port[0]},${zookeeper-hostname[1]}:${zookeeper-port[1]},${zookeeper-hostname[2]}:${zookeeper-port[2]}
      discovery:
        enabled: true
        register: true

zookeeper-hostname: [192.168.6.110,192.168.6.111,192.168.6.112]
zookeeper-port: [2181,2181,2181]
